language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mehbubhasan/docker-react -f Dockerfile.dev .
script:
  - docker run -e mehbubhasan/docker-react npm run test -- -- coverage
  